In [1]:
import numpy as np

In [3]:
#1
print(np.__version__)

2.3.4


In [4]:
#2
listt=[12.23, 13.32, 100, 36.32]
arr=np.array(listt)
print(arr)

[ 12.23  13.32 100.    36.32]


In [13]:
#3
arr2=np.arange(2,11)
arrs=arr2.reshape(3,3)
arrs

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [27]:
#4
arr3=np.zeros((1,10))
arr3
arr3[0,5]=11
arr3

array([[ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.]])

In [28]:
#5
arr4=np.arange(12,38)
arr4

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

In [30]:
#6
arr5=arr4[::-1]
arr5

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

In [36]:
#7
arr6=np.arange(1,5,dtype="float")
arr6


array([1., 2., 3., 4.])

In [53]:
#8
arr7=np.ones((6,6))
#arr7
arr7[1:-1,1:-1]=0
arr7

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [59]:
#9
arr8=np.ones((4,4))
arr8 = np.pad(arr8, pad_width=1, mode='constant', constant_values=0)
arr8 ##gpt

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [67]:
#10
#1ci tek 2-ci cut olanalr ve 1ci cut ikinci tek olanlar 0 olsun ikisi de cutdurse ve ya tekdirse 1 olsun
arr9=np.zeros((8,8))

for i in range(8):
    for j in range(8):
        if (i % 2 == j % 2):
            arr9[i, j] = 1

print(arr9)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [74]:
#11
listt1=[1, 2, 3, 4, 5, 6, 7, 8]
arr10=np.array(listt1)
print(arr10)

tuple1=([8,4,6],[1,2,3])
arr11=np.array(tuple1)
print(tuple1)

[1 2 3 4 5 6 7 8]
([8, 4, 6], [1, 2, 3])


In [85]:
#12(1)
arr12=np.array([10,20,30])
arr13=np.array([40,50,60,70,80,90])
arr14=np.append(arr12,arr13)
arr14

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [86]:
#12(2)
arr12=np.array([10,20,30])
arr13=np.append(arr12,[40,50,60,70,80,90])

arr13

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [100]:
#13
arr15=np.full((3,3),6)
arr15


array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [117]:
#13
arr16=np.empty((3,4),dtype="float")
arr16

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [122]:
#14
#
arr17=np.array([0, 12, 45.21, 34, 99.91])
arr17
x=(arr17-32)*5/9
print(x)

[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


In [125]:
#15
arr18=np.array([ 1.00000000+0.j,0.70710678+0.70710678j])
#arr18
#.real and .imag
real_part=arr18.real
imag_part=arr18.imag

print("real part of array: ",real_part)
print("imaginary part of array: ",imag_part)


real part of array:  [1.         0.70710678]
imaginary part of array:  [0.         0.70710678]


In [133]:
#16
arr19=np.arange(2,11)
arrz=arr19.reshape(3,3)
#arrz itemsize
size_arr=arrz.size
bytes_arr=arrz.itemsize
element_arr=size_arr*bytes_arr

print("Size of the array:",size_arr)
print("Length of one array element in bytes:",bytes_arr)
print("Total bytes consumed by the elements of the array:",element_arr)

Size of the array: 9
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 72


In [162]:
#17 list kimi

   
arr20= np.array([0, 10, 20, 40, 60])
arr21 = np.array([0, 40])
result=[]
for i in range(len(arr20)):
    if arr20[i] in arr21:
        result.append(True)
    else:
        result.append(False)
print(result)

#17 array kimi
arr20 = np.array([0, 10, 20, 40, 60])
arr21 = np.array([0, 40])

print(np.isin(arr20, arr21)) ##in1t

[True, False, False, True, False]
[ True False False  True False]


In [163]:
#18 list kimi
arr22= np.array([0, 10, 20, 40,60])
arr23 = np.array([10,30,40])
result=[]
for i in range(len(arr23)):
    if arr23[i] in arr22:
        result.append(int(arr23[i]))

print(result)


#18 array kimi
arr22 = np.array([0, 10, 20, 40,60])
arr23 = np.array([10,30,40])
com_el = np.intersect1d(arr22, arr23)
print(com_el)


[10, 40]
[10 40]


In [171]:
#19
arr24=np.array([10,10, 20, 20, 30, 30])
un_arr=np.unique(arr24)
print(un_arr)

arr25=np.array([[1, 1],
[2 ,3]])
un2_arr=np.unique(arr25)
print(un2_arr)

[10 20 30]
[1 2 3]


In [176]:
#20
arr26=[ 0 ,10, 20, 40, 60, 80]
arr27=[10, 30, 40, 50, 70, 90]
dif_arr=np.setdiff1d(arr26,arr27)
print(dif_arr)

#diff array elemenleti arasibnda ferq

[ 0 20 60 80]
