In [6]:
# 1
# array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57]) yaradin


import numpy as np
arr=np.array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57])


In [9]:
# 2
# array([[ 0,  3,  6,  9, 12],
#        [15, 18, 21, 24, 27],
#        [30, 33, 36, 39, 42],
#        [45, 48, 51, 54, 57]]) formasina cevirin


arr1=arr.reshape(4,5)
arr1

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27],
       [30, 33, 36, 39, 42],
       [45, 48, 51, 54, 57]])

In [36]:
# 3
# Yuxaridaki arraydan asagidaki hisseni cap edin
# array([[18, 21, 24],
#        [33, 36, 39],
#        [48, 51, 54]])


arr1[1:,1:4]

array([[18, 21, 24],
       [33, 36, 39],
       [48, 51, 54]])

In [22]:
# 4
# sutun uzre cemi tapin : array([ 90, 102, 114, 126, 138])

np.sum(arr1,axis=0)

array([ 90, 102, 114, 126, 138])

In [42]:
# 5
# nested forla her bir ededi cixarin

for i in range(len(arr1)):
    for j in range(len(arr1[i])):
        print(arr1[i][j])

0
3
6
9
12
15
18
21
24
27
30
33
36
39
42
45
48
51
54
57


In [44]:
# 6
# array([36, 51]) secin

arr1

arr1[2:,2:3]

array([[36],
       [51]])

In [46]:
# 7
# max tap
np.max(arr1)

np.int64(57)

In [53]:
# 8
# 0-11 araliginda beraber paylanan 6 ededden ibaret array yaradin


arr11=np.linspace(0,11,6)
arr11

array([ 0. ,  2.2,  4.4,  6.6,  8.8, 11. ])

In [62]:
# 9
# esas diagonali 1lerden ibaret array yaradin
# array([[1., 0., 0., 0., 0., 0.],
#        [0., 1., 0., 0., 0., 0.],
#        [0., 0., 1., 0., 0., 0.],
#        [0., 0., 0., 1., 0., 0.],
#        [0., 0., 0., 0., 1., 0.],
#        [0., 0., 0., 0., 0., 1.]])



arr12=np.identity(6)
arr12

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [63]:
# 10
# Yaradin
# array([[1., 3., 3.],
#        [3., 1., 3.],
#        [3., 3., 1.]])
arr14=np.identity(3)

arr13=np.where(arr14==0,3,arr14)
arr13

array([[1., 3., 3.],
       [3., 1., 3.],
       [3., 3., 1.]])

In [76]:
# 11
# [[1. 0. 0.]
#  [3. 3. 0.]
#  [3. 3. 1.]]

arr15=np.identity(3)
arr15[1:,:2]=3
arr15

array([[1., 0., 0.],
       [3., 3., 0.],
       [3., 3., 1.]])

In [77]:
import numpy as np
a = np.random.randn(3, 3)
b = np.where(a>0, '+', '-')
b

array([['-', '+', '-'],
       ['-', '-', '+'],
       ['+', '+', '-']], dtype='<U1')

In [87]:
# 12
# loopdan istifade ederek a arrayine esasen b arrayini ozunuz yaradin

b_new=np.empty((3, 3), dtype='str')
b_new

for i in range(len(a)):
    for j in range(len(a[i])):
        if a[i][j]>0:
            b_new[i][j]='+'
        else:
            b_new[i][j]='-'
b_new

array([['-', '+', '-'],
       ['-', '-', '+'],
       ['+', '+', '-']], dtype='<U1')

In [88]:
# 13
m = [[1,2,3,4,5],
     [6,7,8,9,10],
     [11,12,13,14,15]]
k = np.array(m)
k

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [91]:
# where methodundan istifade ederek k arrayine esasen asagidaki arrayi yaradin
# array([['Tek', 'Cut', 'Tek', 'Cut', 'Tek'],
#        ['Cut', 'Tek', 'Cut', 'Tek', 'Cut'],
#        ['Tek', 'Cut', 'Tek', 'Cut', 'Tek']]

#arr13=np.where(arr14==0,3,arr14)


arr17=np.where(k%2==0,'Cut','Tek')
arr17

array([['Tek', 'Cut', 'Tek', 'Cut', 'Tek'],
       ['Cut', 'Tek', 'Cut', 'Tek', 'Cut'],
       ['Tek', 'Cut', 'Tek', 'Cut', 'Tek']], dtype='<U3')

In [101]:
# 14
# 20den boyuk 3e bolunen ededleri qaytarmaq ucun where methodundan istifade edin


arr18=k[np.where((k%3==0) & (k>20))]
arr18

array([], dtype=int64)

In [140]:
# 15
# A - 1-dən 10-a qədər dəyərləri olan tək ölçülü bir array qurun. Sonra bu array-də təkcə 2-yə bölünən ədədləri saxlayin. [2, 4, 6, 8, 10]
# B – Təkcə 2-yə bölünən ədədləri 0 ilə əvəzləyin. [1, 0, 3, 0, 5, 0, 7, 0, 9, 0]





arr19=np.arange(1,11,1)
#arr19

#A
arr20=arr19[np.where(arr19%2==0)]
arr20


array([ 2,  4,  6,  8, 10])

In [136]:
#B
arr21=np.where(arr19%2==1,arr19,0)
arr21

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

In [143]:
# 16
# A - 1-dən 10-a qədər dəyərləri olan tək ölçülü bir array qurun.
# B – Cüt olan ədədləri -1-lə hasilini tapın. [1, -2, 3, -4, 5, -6, 7, -8, 9, -10]

arr22=np.arange(1,11,1)
arr23=np.where(arr19%2==0,-1*arr19,arr19)
arr23

array([  1,  -2,   3,  -4,   5,  -6,   7,  -8,   9, -10])

In [154]:
# 17
# Arrayın bütün elementlərini onun ortlaması ilə əvəzləyin. [1, 2, 4, 7] --- [3.5, 3.5, 3.5, 3.5]

arr24=np.arange(1,11,2)
#arr24
arr24[:]=np.mean(arr24)
arr24


array([5, 5, 5, 5, 5])

In [163]:
# 18
# 2 dənə birölçülü array verilib bu arrayların fərqinin kvadratını çıxarın.
arr25=np.arange(1,20,2)
arr26=np.arange(1,11,1)
arr25
arr27=(arr25-arr26)**2
arr27

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [192]:
# 19
# Elə bir array yaradın ki, 15 elementli olsun, (5x3) olsun və düz ortadakı ədədin qiymətini -15 qoyun

arr28=np.arange(1,16,1)
arr29=arr28.reshape(5,3)
arr29[2:3,1:2]=-15
arr29

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7, -15,   9],
       [ 10,  11,  12],
       [ 13,  14,  15]])

In [212]:
# 20
# 0:200 arasında təsadüfi dəyərlərə sahib 10x10 bir array yaradın. Bu arrayi aşağıdakı kimi filtrləyin:
#      a.1-ci sətirdən başlayaraq hər 3 sətirdən birini seçsin;
#      b.2-ci sütundan başlayaraq hər 2 sütundan birini seçsin
#      c.Matrixin axırıncı sətrini sıfırlarla dəyişdirin


arr30=np.random.randint(0,200,size=(10,10))
arr30

rows1= arr30[0::3]
#rows2=arr30[0::2]
#arr30[9]=0
#arr30